---
- name: Create vaultwarden secrets
  ansible.builtin.include_role:
    name: podman_secrets
  vars:
    podman_secrets_values:
      vaultwarden_admin_token: "{{ lookup('env', 'VAULTWARDEN_ADMIN_TOKEN') }}"

- name: Deploy vaultwarden Quadlets
  ansible.builtin.include_role:
    name: podman_quadlet
  vars:
    podman_quadlet_restart_required: "{{ podman_secrets_create.changed }}"
    podman_quadlet_units:
      - name: vaultwarden.network
      - name: vaultwarden-data.volume
      - name: vaultwarden.container
