all:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3.12
  children:
    bootc_hosts:
      hosts:
        rg-semaphore01:
          ansible_host: 10.6.13.20
        rg-identity01:
          ansible_host: 10.6.13.21
        rg-data01:
          ansible_host: 10.6.13.22
    semaphore_hosts:
      hosts:
        rg-semaphore01:
    identity_hosts:
      hosts:
        rg-identity01:
    data_hosts:
      hosts:
        rg-data01:
    apps_hosts:
      hosts: {}
