all:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3.12
  children:
    bootc_hosts:
      hosts:
        rg-semaphore01:
          ansible_host: 10.6.13.20
    semaphore_hosts:
      hosts:
        rg-semaphore01:
    secrets_hosts:
      hosts: {}
    data_hosts:
      hosts: {}
    apps_hosts:
      hosts: {}
