---
ryan_ssh_public_key: "{{ lookup('env', 'RYAN_SSH_PUBLIC_KEY') }}" # noqa: var-naming[no-role-prefix]
ryan_password_hash: "{{ lookup('env', 'RYAN_PASSWORD_HASH') }}" # noqa: var-naming[no-role-prefix]
