---
immich_quadlet_units:
  - name: immich.network
    enabled: false
    sections:
      - name: Unit
        options:
          Description: Immich bridge network
      - name: Network
        options:
          NetworkName: immich

  - name: immich-library.volume
    enabled: false
    sections:
      - name: Unit
        options:
          Description: Immich library volume
      - name: Volume
        options:
          VolumeName: immich-library
          Type: nfs
          Device: ":/mnt/Storage/immich"
          Options: addr=10.6.13.5,rw

  - name: immich-model-cache.volume
    enabled: false
    sections:
      - name: Unit
        options:
          Description: Immich model cache volume
      - name: Volume
        options:
          VolumeName: immich-model-cache

  - name: immich-postgres.volume
    enabled: false
    sections:
      - name: Unit
        options:
          Description: Immich Postgres data volume
      - name: Volume
        options:
          VolumeName: immich-postgres

  - name: immich-redis.container
    sections:
      - name: Unit
        options:
          Description: Immich Redis
      - name: Container
        options:
          ContainerName: immich_redis
          Image: docker.io/valkey/valkey:9@sha256:8e8d64b405ce18f41b8e5ee20aa4687a8ed0022d1298f2ce31cdcf3a76e09411
          UserNS: auto
          Network: immich.network
          NetworkAlias: immich-redis
          HealthCmd: redis-cli ping || exit 1
      - name: Service
        options:
          Restart: always
      - name: Install
        options:
          WantedBy: multi-user.target

  - name: immich-database.container
    sections:
      - name: Unit
        options:
          Description: Immich Postgres
          Requires: immich-postgres-volume.service
          After: immich-postgres-volume.service
      - name: Container
        options:
          ContainerName: immich_postgres
          Image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
          UserNS: auto
          Network: immich.network
          NetworkAlias: immich-database
          Environment:
            - POSTGRES_PASSWORD_FILE=/run/secrets/immich_db_password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=immich
            - POSTGRES_INITDB_ARGS=--data-checksums
          Volume: immich-postgres.volume:/var/lib/postgresql/data:idmap
          ShmSize: 128m
          Secret: immich_db_password,target=/run/secrets/immich_db_password
      - name: Service
        options:
          Restart: always
      - name: Install
        options:
          WantedBy: multi-user.target

  - name: immich-machine-learning.container
    sections:
      - name: Unit
        options:
          Description: Immich Machine Learning
          Requires: immich-model-cache-volume.service
          After: immich-model-cache-volume.service
      - name: Container
        options:
          ContainerName: immich_machine_learning
          Image: ghcr.io/immich-app/immich-machine-learning:v3
          UserNS: auto
          AutoUpdate: registry
          Pull: newer
          Network: immich.network
          NetworkAlias: immich-machine-learning
          Environment:
            - TZ=America/New_York
            - UPLOAD_LOCATION=./library
            - DB_DATA_LOCATION=./postgres
            - IMMICH_VERSION=v3
            - DB_HOSTNAME=immich-database
            - DB_USERNAME=postgres
            - DB_PASSWORD_FILE=/run/secrets/immich_db_password
            - DB_DATABASE_NAME=immich
            - REDIS_HOSTNAME=immich-redis
          Volume: immich-model-cache.volume:/cache:idmap
          Secret: immich_db_password,target=/run/secrets/immich_db_password
      - name: Service
        options:
          Restart: always
      - name: Install
        options:
          WantedBy: multi-user.target

  - name: immich-server.container
    sections:
      - name: Unit
        options:
          Description: Immich Server
          Requires: immich-library-volume.service
          After: immich-library-volume.service
      - name: Container
        options:
          ContainerName: immich_server
          Image: ghcr.io/immich-app/immich-server:v3
          UserNS: auto
          AutoUpdate: registry
          Pull: newer
          Network: immich.network
          PublishPort: "2283:2283"
          NetworkAlias: immich-server
          Environment:
            - TZ=America/New_York
            - UPLOAD_LOCATION=./library
            - DB_DATA_LOCATION=./postgres
            - IMMICH_VERSION=v3
            - DB_HOSTNAME=immich-database
            - DB_USERNAME=postgres
            - DB_PASSWORD_FILE=/run/secrets/immich_db_password
            - DB_DATABASE_NAME=immich
            - REDIS_HOSTNAME=immich-redis
          Volume:
            - immich-library.volume:/data
          Secret: immich_db_password,target=/run/secrets/immich_db_password
      - name: Service
        options:
          Restart: always
      - name: Install
        options:
          WantedBy: multi-user.target
