---
- name: Upgrade bootc hosts
  hosts: bootc_hosts
  become: true
  tasks:
    - name: Upgrade bootc host image
      ansible.builtin.command:
        cmd: bootc upgrade
      register: bootc_upgrade
      changed_when: "'No changes' not in bootc_upgrade.stdout"

    - name: Reboot into new deployment
      ansible.builtin.reboot:
      when: bootc_upgrade.changed
