---
- name: Deploy Immich
  hosts: data_hosts
  become: true
  vars:
    podman_secrets:
      immich_db_password: "{{ lookup('env', 'IMMICH_DB_PASSWORD') }}"
  roles:
    - podman_subids
    - podman_secrets
    - immich
    - podman_quadlet
