---
- name: Configure mutable host settings
  ansible.builtin.import_playbook: host_config.yml

- name: Enroll bootc hosts with NetBird
  ansible.builtin.import_playbook: netbird.yml

- name: Deploy Semaphore UI
  ansible.builtin.import_playbook: semaphore.yml

- name: Deploy Vaultwarden
  ansible.builtin.import_playbook: vaultwarden.yml

- name: Deploy Immich
  ansible.builtin.import_playbook: immich.yml

- name: Deploy OpenCloud
  ansible.builtin.import_playbook: opencloud.yml
