---
- name: Create immich secrets
  ansible.builtin.include_role:
    name: podman_secrets
  vars:
    podman_secrets_values:
      immich_db_password: "{{ lookup('env', 'IMMICH_DB_PASSWORD') }}"

- name: Deploy immich Quadlets
  ansible.builtin.include_role:
    name: podman_quadlet
  vars:
    podman_quadlet_restart_required: "{{ podman_secrets_create.changed }}"
    podman_quadlet_units:
      - name: immich.network
      - name: immich-library.volume
      - name: immich-model-cache.volume
      - name: immich-postgres.volume
      - name: immich-redis.container
      - name: immich-database.container
      - name: immich-machine-learning.container
      - name: immich-server.container
