---
- name: Enforce Ansible service account policy
  ansible.builtin.user:
    name: ansible
    groups:
      - wheel
    append: true
    shell: /bin/bash
    password_lock: true

- name: Ensure Ansible SSH directory permissions
  ansible.builtin.file:
    path: /home/ansible/.ssh
    state: directory
    owner: ansible
    group: ansible
    mode: "0700"

- name: Enforce Ryan account policy
  ansible.builtin.user:
    name: ryan
    groups:
      - wheel
    append: false
    shell: /bin/bash

- name: Configure Ryan password
  ansible.builtin.user:
    name: ryan
    password: "{{ ryan_password_hash }}"
    password_lock: false
    update_password: always
  when: ryan_password_hash | length > 0
  no_log: true

- name: Ensure Ryan SSH directory exists
  ansible.builtin.file:
    path: /home/ryan/.ssh
    state: directory
    owner: ryan
    group: ryan
    mode: "0700"
  when: ryan_ssh_public_key | length > 0
  no_log: true

- name: Configure Ryan SSH key
  ansible.builtin.copy:
    dest: /home/ryan/.ssh/authorized_keys
    content: "{{ ryan_ssh_public_key }}\n"
    owner: ryan
    group: ryan
    mode: "0600"
  when: ryan_ssh_public_key | length > 0
  no_log: true
