NETBIRD_SETUP_KEY: ""
RYAN_SSH_PUBLIC_KEY: ""
RYAN_PASSWORD_HASH: ""
VAULTWARDEN_ADMIN_TOKEN: ""
IMMICH_DB_PASSWORD: ""
OPENCLOUD_ADMIN_PASSWORD: ""
OPENCLOUD_COLLABORA_ADMIN_PASSWORD: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdzgvSUhEQkFoKzV6WlFt
            R2hMeDlIRkE5aU5jZ3B4MVVZakIxQ3NRNkFnCkYvTE9FZXF5dHRiQWdsUzlRd1lI
            Q3hScUZVT295dGZaMWFPVm82WnR5NDAKLS0tIHY5VDJiRkN1Si8vQ0R0Q1FWNzc1
            YS9MMGRUUktMSnlFcXU0eE9XVFR2ajgKJpbUZSMK/hs0xnh0nP/sOjuJnXenwiye
            NR7fkgdcNHDRdoeesqBsuNOgKK+dwAaExewYNcPXXjPIQdHfzoNeEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age129jp0n9xx5jmsvaccahv5tvfx072rw3jk75qnvaevjfkppt3fsgqa38qxk
    lastmodified: "2026-09-21T18:38:52Z"
    mac: ENC[AES256_GCM,data:CF1c6kCsxuwWyzgkt2BxhFjmoFm1pSzPkd4R2rGyfoJppWzCJtS1ab3cTS/aGlP7lkYeyzKypzgGXtu7mEl46xqT9m8ODH40nO7nSP3vZCIuaB7SxZazFjztnQ0XHmZvnbW8FnF1P7Y7QHQM0Pk7DfrgM1q6cMi56c/wB4HQI4M=,iv:+SaS3StHqMhG9kF9VaQbzRXVBZeYs+V4nsrl+h/MXQo=,tag:5UCI3BJrqiJS+57iFph3Vw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
