NETBIRD_SETUP_KEY: ENC[AES256_GCM,data:MAd894AunAofuXne2M43gJavTzzs68wXuiWA+2JQ0rHcJtu1,iv:FBTyXvuRW42SaPzWtnQp5FOKcLckukrxXVT90wYtWTM=,tag:6RXXqgATxNiytagtJunFxw==,type:str]
RYAN_SSH_PUBLIC_KEY: ENC[AES256_GCM,data:zEmwQQ5HPd0dKtEJ2Y2+agkT42XIzyuW999RGZYJ5FC/sQEAEL7u0xmjzbjJsPHx8NtcbqHQCaRNryT/eU1JpLWOwT+DsizODO3KY7Rc3Ys=,iv:ihsTc+MWF4u0IkjmGj7j7ZZ68C40Em/3bgOyTD6uc0E=,tag:bnFvbipXiFhswsrSCCKo2g==,type:str]
RYAN_PASSWORD_HASH: ENC[AES256_GCM,data:ObCh830KW+XHm9P0hRa6uu3jQCsXP8HRoQ96vq3SdsxM21+HfnwymUMmGYrjBRp6J4WIijsYQimC42nDEWE1WOawePWH8AmAeSVJMk8aj++g2K39v2oV2uW83qkk/jOKLEebrcuRTWMxNA==,iv:BMrTuKtuB+R54LvZ1S7lZf0os1uanwOCQQpkCbSdwxY=,tag:HAZu5JmDHDMrfwDYDjw5ww==,type:str]
VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:Q6TeDR2Fj5If3lJgjT4meg4JKzZj+Kvti2juKIBzLkWE68MD72oS5bcR69wSHOhJ01Nn9uuWOEe0mUItHWEw1ghMn5IYkPActXc7kk6YZlTwxYiOElO++91ZmZ5+zQTG,iv:/nZAY8+Uytwovlq6SfAn4XJw1qiR4AIYmX2ccBhERd8=,tag:8H5hHbwxrrSw2drA5ipg0Q==,type:str]
IMMICH_DB_PASSWORD: ENC[AES256_GCM,data:kNmO1Ips2ooQ7Flxxky4/o/qYnSoioQ/3xk1Rkz9NVktCutiOAKWmhvLl3Z7y2z/afK5H+dbpFS//Tv2qwDEtw==,iv:yXb75W1hYBwdayHO17DUKqV5Ww8R4M4oln/9Y0L96J8=,tag:DygQLqfAp2DdnwsfDWExLg==,type:str]
OPENCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:cj/QiHcy9fb4n5h8XIrlsqhn4aPMZfxUqsa5Sg==,iv:vjWTMyQ0acTB3oCh17SLdHGzYNjhwst/Fjsy4x/AhQk=,tag:LIhJ2vt3ScJcE4KGVJD+gg==,type:str]
ONLYOFFICE_JWT_SECRET: ENC[AES256_GCM,data:YgE5gZLJa54TUapNI/wT6h8c/BzEBJ8vOSnM+e7dB2179HAwbfAwS0GwKBEaNG5Sl4h1kEzYrAUeSfzz6DV4+A==,iv:Hf+CTIoCffItDUp/bSt1NqwlL/W65x/ZZ9Ihq3N4vec=,tag:CtNbkcaQJaiOVuQ1uz6PkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdzgvSUhEQkFoKzV6WlFt
            R2hMeDlIRkE5aU5jZ3B4MVVZakIxQ3NRNkFnCkYvTE9FZXF5dHRiQWdsUzlRd1lI
            Q3hScUZVT295dGZaMWFPVm82WnR5NDAKLS0tIHY5VDJiRkN1Si8vQ0R0Q1FWNzc1
            YS9MMGRUUktMSnlFcXU0eE9XVFR2ajgKJpbUZSMK/hs0xnh0nP/sOjuJnXenwiye
            NR7fkgdcNHDRdoeesqBsuNOgKK+dwAaExewYNcPXXjPIQdHfzoNeEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age129jp0n9xx5jmsvaccahv5tvfx072rw3jk75qnvaevjfkppt3fsgqa38qxk
    lastmodified: "2026-09-22T16:38:08Z"
    mac: ENC[AES256_GCM,data:+W5WNpMSiB4zbygLY8DrdkKYuIlADHcGzHvwF9UafUBYqHwSMT3/RA4rT8eQEUi6s6vMOS5veDFwjj1VZx7D0/IJe1CotBtmft9aM6gHlZRIp4bav+yJWugQVOViriT8XOGZYcXJbLe0ExSMcAtbR60ZDFiOaOg16hO3QKhunYo=,iv:2Ahz5PkPb2gSIJpPVAQUg+xIxeLtEnPhZF8LcS7Lo+0=,tag:SpRrRXanAcHVjjnCf422iQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
